### ISSUE TITLE
.tracesTest failed but condition is TRUE

### ISSUE THREAD

**Issue by anfoss** [CCprofiler/CCprofiler#10]
Following correct importPCP (no error)
`pepTraces_cons <- filterConsecutiveIdStretches(traces = pepTraces, min_stretch_length = 3)`
raises Error in .tracesTest(traces) : 
  IDs in traces and trace_annotation are not identical.

However when tested manually

`identical(names(pepTraces$traces), c(pepTraces$fraction_annotation$id, "id"))`
TRUE

Problem is that there is implicit type conversion from factor to character of pepTraces$traces$id.

This solutions are both working
Disabling . tracesTest solved the issue
Convert both pepTraces$traces$id, pepTraces$trace_annotation$id to character solved the issue. I can provide a pull request with both solutions and fixed function to avoid this bug.

**Comment by ibludau** [comment]
Thanks for pointing this out. Feel free to make a pull request for a fix.
